### ISSUE TITLE
Error while loading localisation_cues.pickle

### ISSUE THREAD

**Issue by brijkr** [xtudbxk/SEC-tensorflow#10]
Hi, While loading cues file as instructed, i am facing following issue---->
_pickle.UnpicklingError: invalid load key, '\x0a'.

**Comment by xtudbxk** [comment]
Maybe the problem is because that you didn't extract the data from the downloaded file. And following the instructions from the SEC-caffe project, you should extract it with "gzip -kd localization_cues.pickle.gz". 
So in totally, to prepare the cues datas, you have three  detailed steps to do:
1. download the cues data
2. put it in data folder
3. uncompress it by "gzip -kd localization_cues.pickle.gz" 

May those steps help you ~

**Comment by brijkr** [comment]
I have extract data using gzip -kd  command ; 
FYI:
I am using anaconda3 (python 3.6) I followed all instructions 
One more thing I am using windows 7. Do you think this problem is because of window 7?

**Comment by xtudbxk** [comment]
oh, I have no idea what the problem is. And it works well in python3.6 or window 7 in my test cases. Maybe you can download the data again and see if the problem happens.

**Comment by brijkr** [comment]
Thank you, downloading again worked.
Now I am facing another problem, i am not if i should create another issue with appropriate name or should i ask it here itself, so i am asking it.
you have used tf.data*** at 73rd line of dataset.py file which is giving following error--->
AttributeError: module 'tensorflow' has no attribute 'data'
As per my knowledge, tensorflow does not have such option. can you please help me ?
thanks

**Comment by xtudbxk** [comment]
I just add some information about the version of tensorflow. And it seems that you use tensorflow 2.0 while the project needs tensorflow 1.14.0.  To my knowledge, any tensorflow which version is less than 2.0 is compatiable with this project.

**Comment by brijkr** [comment]
Hello, Can you please add information regarding CUDA version and driver version as well. I am getting a error "CUDA driver version is insufficient for CUDA runtime version"
Thanks

**Comment by xtudbxk** [comment]
I'm not familiar with those information. And it seems your gpus didn't work well. Maybe you can search it on google or baidu.
